version: '3.8'

services:
  web:
    build: .
    command: gunicorn --config gunicorn.conf.py rentora_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-prod-key-rentora-change-in-prod
      - ALLOWED_HOSTS=*
    restart: always

volumes:
  static_volume:
  media_volume:
