# Generated by Django 6.0.7 on 2026-07-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField(default=9.9312)),
                ('lng', models.FloatField(default=76.2673)),
                ('category', models.CharField(choices=[('Luxury Villa', 'Luxury Villa'), ('Backwater Estate', 'Backwater Estate'), ('Hill Retreat', 'Hill Retreat'), ('Heritage Home', 'Heritage Home'), ('Penthouse Suite', 'Penthouse Suite'), ('Coastal Residence', 'Coastal Residence'), ('Studio Loft', 'Studio Loft')], default='Luxury Villa', max_length=100)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('area', models.IntegerField(help_text='Area in sq.ft')),
                ('furnished', models.BooleanField(default=True)),
                ('parking', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.CharField(help_text='Main image path or URL', max_length=500)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(max_length=150)),
                ('renter_email', models.EmailField(max_length=254)),
                ('renter_phone', models.CharField(max_length=50)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending ⏳'), ('Approved', 'Approved ✅'), ('Declined', 'Declined ❌'), ('Cancelled', 'Cancelled 🚫')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_list', to='rentals.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='rentals.property')),
            ],
        ),
    ]
